version: '3.8'

services:
  # MailHog for email testing
  mailhog:
    image: mailhog/mailhog:v1.0.1
    platform: linux/amd64  # Specify platform for Apple Silicon compatibility
    container_name: campus_locker_mailhog_dev
    ports:
      - "1025:1025"  # SMTP server
      - "8025:8025"  # Web UI
    restart: unless-stopped

  # Main Application (Development)
  app:
    build: 
      context: ./campus_locker_system
      dockerfile: Dockerfile.dev
    container_name: campus_locker_app_dev
    ports:
      - "5001:5000"  # Use port 5001 externally to avoid conflict with macOS Control Center
    environment:
      # Flask Configuration
      - FLASK_ENV=development
      - FLASK_APP=run.py
      - FLASK_DEBUG=1
      - SECRET_KEY=dev-secret-key-not-for-production
      
      # Database Configuration (SQLite)
      - DATABASE_URL=sqlite:////app/databases/campus_locker_dev.db
      - SQLALCHEMY_DATABASE_URI=sqlite:////app/databases/campus_locker_dev.db
      - AUDIT_DATABASE_URL=sqlite:////app/databases/campus_locker_audit_dev.db
      
      # Email Configuration
      - MAIL_SERVER=mailhog
      - MAIL_PORT=1025
      - MAIL_USE_TLS=False
      - MAIL_USE_SSL=False
      - MAIL_USERNAME=
      - MAIL_PASSWORD=
      - MAIL_DEFAULT_SENDER=noreply@campuslocker.local
      
      # Application Configuration
      - PARCEL_MAX_PICKUP_DAYS=7
      - PARCEL_DEFAULT_PIN_VALIDITY_DAYS=7
      - ENABLE_LOCKER_SENSOR_DATA_FEATURE=true
      - DEFAULT_LOCKER_SENSOR_STATE_IF_UNAVAILABLE=false
      
      # Logging
      - LOG_LEVEL=DEBUG
      - LOG_FILE=/app/logs/campus_locker_dev.log
    
    volumes:
      # Mount source code for live reloading
      - ./campus_locker_system:/app
      - dev_logs:/app/logs
      - dev_databases:/app/databases
    
    depends_on:
      - mailhog
    
    restart: unless-stopped

volumes:
  dev_logs:
    driver: local
  dev_databases:
    driver: local

networks:
  default:
    name: campus_locker_dev_network 