version: '3.8'
services:
  mailhog:
    image: mailhog/mailhog:v1.0.1
    container_name: mailhog
    ports:
      - "1025:1025"  # SMTP server
      - "8025:8025"  # Web UI
    restart: unless-stopped 
  app:
    build: ./campus_locker_system
    container_name: campus_locker_app
    command: python run.py
    ports:
      - "5001:5000"
    volumes:
      - ./campus_locker_system/databases:/app/databases
    depends_on:
      - mailhog
    environment:
      - FLASK_ENV=development 
      - MAIL_SERVER=mailhog 
